# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 784d6a0e72123d38db66b7f8bcce16293f4c0627d9f5f46cff651020f05e27bb1918953efbed3b6f7dbfb2007192dc3d35b5cd428018bcf74a9732841fb44afd

test:
  secret_key_base: fcb9aa10665bc029ecf07ca239ea07aef64c67f2f661b283dc94e2186a9499fae3ee9906d7e6cba8fbe801512245e873546f7e553f503c36a68f4c6e28fce5a0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
